//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBade
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBContext : DbContext
    {
        public DBContext()
            : base("name=DBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<t_comment> t_comment { get; set; }
        public virtual DbSet<t_composition> t_composition { get; set; }
        public virtual DbSet<t_compositiongenre> t_compositiongenre { get; set; }
        public virtual DbSet<t_genre> t_genre { get; set; }
        public virtual DbSet<t_user> t_user { get; set; }
        public virtual DbSet<t_userlikes> t_userlikes { get; set; }
    }
}
