//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBade
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_composition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_composition()
        {
            this.t_comment = new HashSet<t_comment>();
            this.t_compositiongenre = new HashSet<t_compositiongenre>();
            this.t_userlikes = new HashSet<t_userlikes>();
        }
    
        public int id_composition { get; set; }
        public int id_user { get; set; }
        public string name { get; set; }
        public Nullable<long> duration { get; set; }
        public string description { get; set; }
        public string artists { get; set; }
        public string composers { get; set; }
        public string album { get; set; }
        public Nullable<int> compos_year { get; set; }
        public Nullable<bool> is_visible { get; set; }
        public string composition_url { get; set; }
        public string albumcover { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_comment> t_comment { get; set; }
        public virtual t_user t_user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_compositiongenre> t_compositiongenre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_userlikes> t_userlikes { get; set; }
    }
}
