//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meow_Band.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_Context : DbContext
    {
        public DB_Context()
            : base("name=DB_Context")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            //throw new UnintentionalCodeFirstException();
            //        modelBuilder.Entity<Person>()
            //.HasOptional(p => p.Creator)
            //.WithMany(p => p.Created).
            //.HasForeignKey(p => p.CreatorId);
            modelBuilder.Entity<t_user>().HasKey(p => p.id_user).HasMany(p=>p.t_composition).WithMany();
            modelBuilder.Entity<t_genre>().HasKey(p => p.id_genre);
            modelBuilder.Entity<t_composition>().HasKey(k => k.id_composition);
                //base.OnModelCreating(modelBuilder);

        }
    
        public virtual DbSet<t_comment> t_comment { get; set; }
        public virtual DbSet<t_composition> t_composition { get; set; }
        public virtual DbSet<t_compositiongenre> t_compositiongenre { get; set; }
        public virtual DbSet<t_genre> t_genre { get; set; }
        public virtual DbSet<t_user> t_user { get; set; }
        public virtual DbSet<t_userlikes> t_userlikes { get; set; }
    }
}
