//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meow_Band.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class t_comment
    {
        [Key]
        public int id_comment { get; set; }
        public int id_user { get; set; }
        public int id_composition { get; set; }
        public string comment_text { get; set; }
        public Nullable<System.DateTime> comment_date { get; set; }
    
        public virtual t_composition t_composition { get; set; }
        public virtual t_user t_user { get; set; }
    }
}
